spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/HackGT?createDatabaseIfNotExist=true
    username: root
    password: database123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false

server:
  address: 0.0.0.0  # Allow connections from any IP
  port: 8080